export const BANK = {
  KOOKMIN: '국민은행',
  SHINHAN: '신한은행',
  HANA: '하나은행',
  WOORI: '우리은행',
  IBK: '기업은행',
  NONGHYUP: '농협은행',
  SUHYEOP: '수협은행',
  CITI: '씨티은행',
  KDBBANK: '산업은행',
  JEJUBANK: '제주은행',
  GWANGJUBANK: '광주은행',
  JEONBUKBANK: '전북은행',
  BUSANBANK: '부산은행',
};
